### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by warezgibzzz** [nwg-piotr/nwg-wrapper#14]
I want to able able to define a config for wrapper instance in .ini file, so that this (for example) very verbose string
`nwg-wrapper -s swaylock-time.sh -o eDP-1 -r 1000 -c timezones.css -p right -mr 50 -a start -mt 0 -j right -l 3 -sq 31`
can become that
`nwg-wrapper ~/.config/nwg-wrapper/time.ini`

with config file being in that format
```
[wrapper]
script=swaylock-time.sh
output=eDP-1
refresh=1000
css=timezones.css
position=right
margin_right=50
margin_top=0
justify=right
layer=3
sig_quit=31
```

I can implement that feature.

**Comment by nwg-piotr** [comment]
Well, I didn't want config files for nwg-shell stuff other than nwg-panel, but of course it could be added, if you really need it. But use json format, please.

**Comment by warezgibzzz** [comment]
It's not so needed, but i think it's nice to have such option.
I think the same, that it should be an optional feature, so it's users choice, how to configure wrapper instance.
JSON, got it.

**Comment by nwg-piotr** [comment]
To me it's just a small piece of the puzzle I'm trying to do on the level of a [common settings app](https://github.com/nwg-piotr/nwg-shell-config). Having a config file for each part is a complication.

**Comment by warezgibzzz** [comment]
Ah. I understood.
Then i wont do it, i'll better take a look on common settings app and see what i can do there.
Closing the issue :)
