### ISSUE TITLE
CAVA support

### ISSUE THREAD

**Issue by HVisMyLife** [nwg-piotr/nwg-wrapper#17]
Is it possible, to display cava with this? Or any other program?
Thanks in advance

**Comment by nwg-piotr** [comment]
You mean [this](https://github.com/karlstav/cava)? I'm afraid it would be difficult. Just plain or pango-formatted text.

**Comment by HVisMyLife** [comment]
Yes, I was thinking about it, sorry that I forgot to link that.
So for wayland currently there is no way to do that? I was trying to simulate that by floating transparent terminal, but I couldn't put it on bottom layer...

**Comment by nwg-piotr** [comment]
One can always open a window on the layer shell, but I have no idea if it's even possible to open another applications window inside it. TBH I don't see much sense in making desktop widgets for a tiling window manager. They would only be visible on r/unixporn, hardly ever in real life.
