### ISSUE TITLE
No option to specify workspace to draw nwg-wrapper on

### ISSUE THREAD

**Issue by gnull** [nwg-piotr/nwg-wrapper#26]
Nwg-wrapper seems to appear on the currently active workspace. How do I draw it on another one? Can I draw it on all workspaces?

Ivan

**Comment by nwg-piotr** [comment]
It opens on `gtk-layer-shell`, which means: it ignores workspaces. In the same way as panels/bars do. You can only select an output with the `-o` | `--output` argument.

**Comment by gnull** [comment]
Ah, makes sense. Sorry, I somehow missed the -o in the help text.

Would it be a good idea to maybe allow multiple outputs to be
specified so we could use the second one if the first one goes
offline? (Or is it a job for Kanshi?)

I use a docking station with two monitors a lot, so it would be really
good if nwg-wrapper could jump between outputs as I dock/undock my
laptop.

Ivan

**Comment by nwg-piotr** [comment]
Well, I can either specify an output or not. To put the wrapper on two outputs, we'd need two wrapper instances (windows).

**Comment by gnull** [comment]
No, what I mean is: keep it on output-1, but if it gets disconnected move to output-2. So maybe we cold specify multiple outputs in `-o output-1,output-2,output-3`?
