### ISSUE TITLE
Allow different layer for wraper

### ISSUE THREAD

**Issue by Iss-in** [nwg-piotr/nwg-wrapper#3]
Feature request :  to have an option to show wrapper in bottom or top layer.  

infact having an option like waybar where you can send a custom signal to a module will be awesome. an id can be given to wraper window which can be used to toggle surface layer . It sounds a bit over the edge but will be an aweosme option to have

**Comment by nwg-piotr** [comment]
Could you check if it meets your expectations? Use `pkill -USR1 nwg-wrapper` to switch layers.

**Comment by nwg-piotr** [comment]
If I undertand their [wiki](https://github.com/Alexays/Waybar/wiki/Module:-Custom) well, Waybar allows to choose *The signal number used to update the module*, not a window ID, whatever you mean.

**Comment by Figuera** [comment]
This is very useful. Is there, or can we add, an hide signal as well?

I mean I want to send a signal to nwg-wrapper so it become invisible but the process is still running.

**Comment by nwg-piotr** [comment]
The same signal switches the layer both ways.

**Comment by Figuera** [comment]
I got that but meant fully hide as in not visible even if no window is open.

**Comment by nwg-piotr** [comment]
Of course it could be done by just `window.hide()` / `window.show()`. Could you give me a use case to justify the new feature?

**Comment by Figuera** [comment]
To be honest this would be feature request 1/2 to implement my use case.

I want to use the wrapper as a sort of waybar substitute in which when I hold a key the wrapper show me information such as Current Window Title, Time and Weather. But when I release it the wrapper is hidden.

It is already possible to do something like that but I would enjoy to have my background fully visible when no window is open.

My second feature request would be an update signal or an update frequency. So the wrapper can be running in the background but updating time and weather at predetermined frequency.

**Comment by nwg-piotr** [comment]
Couldn't the latter be done inside the script?

I'll take a closer look at this soon. I had some surgery done last Friday, and can't focus well enough on the code at the moment. Will get back to it as soon as I can.

**Comment by Figuera** [comment]
Yeah, thinking about it more deeply I think I can just send a kill signal when I release the key. Will try that.

I wish you the best recovery. Hopefully everything went well in your procedure.
