### ISSUE TITLE
support for application windows

### ISSUE THREAD

**Issue by UltraBlackLinux** [nwg-piotr/nwg-wrapper#30]
Hey there,
I've been searching a tool for quite a while now, that allows me to put an application window into any screen layer.
I think it would be a perfect fit for this project. It would allow me to use programs like mpv (bad example, already has a standalone implementation) as a wallpaper.
Could this be done?
Thanks!

**Comment by nwg-piotr** [comment]
Sorry, it won't work. As described in README, it allows to:

>  display a script output, or a text file content on the desktop in sway or other wlroots-based compositors.

**Comment by UltraBlackLinux** [comment]
that's why I'm trying to request that feature. Sorry if I did not make that clear.

**Comment by nwg-piotr** [comment]
As far as I know, it's impossible inside the GTK framework.

**Comment by UltraBlackLinux** [comment]
oh well. Thanks anyways.
