### ISSUE TITLE
Display on top of swaylock?

### ISSUE THREAD

**Issue by bhepple** [nwg-piotr/nwg-wrapper#5]
I use swaylock to display a random image while locked:

    swaylock --daemonize --image "$IMAGE" &

Is there any way to have nwg-wrapper display some text 'on top of' that image. I tried --layer=2 but it does not display (until I unlock!).

**Comment by nwg-piotr** [comment]
The `-l 3` argument seems to display the wrapper content over swaylock. I'm not sure ATM how switching layers and visibility with signals is going to behave.

**Comment by bhepple** [comment]
You're right! Thanks for that and BTW thanks for all your sway/wl-roots contributions!!

**Comment by nwg-piotr** [comment]
You're welcome! Thanks for featuring them on your and sway Wiki.

**Comment by bhepple** [comment]
I spoke too soon! It seems that the very first time an image is used with swaylock, nwg-wrapper is able to display on top of it. Subsequent runs (using the same image) are not able - although when swaylock terminates (on password entry) the nwg-wrapper window is visible. The effect is preserved even after the sway session is exited and restarted. Each image can be displayed exactly once!!! Quite weird.

    swaylock --image '/home/bhepple/media/backgrounds/Evening at Bilbos-X3.jpg' & 
    nwg-wrapper -s timezones.sh -r 10000 -c timezones.css -p right -mr 50 -a start -mt 50 -j right --layer 3

**Comment by bhepple** [comment]
BTW - hitting a running nwg-wrapper does not fix things, nor does using a different offset eg -mr 100 instead of 50

**Comment by nwg-piotr** [comment]
`sleep 1 &&` seems to help here:

```bash
#!/usr/bin/env bash

nwg-wrapper -s timezones.sh -r 10000 -c timezones.css -p right -mr 50 -a start -mt 50 -j right --layer 3 &
sleep 1 && swaylock --image /home/piotr/Obrazy/Wallpapers/wallhaven-kwxjl6-1920x1080.jpg && pkill -f -2 nwg-wrapper
```
If you need the wrapper content on the lock screen only, you'll probably want to kill it later. Use `SIGINT` (2) or `SIGTERM` (15) for it to terminate safely.

![IMG_20211107_133654](https://user-images.githubusercontent.com/20579136/140645374-77529525-1437-41af-b63e-d3e6fd2c7548.jpg)

**Comment by bhepple** [comment]
That worked! although I need 2s sleep to be reliable. Maybe my system is slow (10yo laptop). Thank you again!!

**Comment by nwg-piotr** [comment]
Tomorrow, when I'm bored enough at the office, I'll check it out on my old, testing laptop. For now only tested on my main machine and dwl compositor.

**Comment by nwg-piotr** [comment]
One more thing: killing the process with signal 2 or 15 terminates all the wrapper instances. I think we need one more argument, like `-sq` | `--sig_quit` to choose a custom signal for a certain instance.

**Comment by 10b14224cc** [comment]
I can't get it to work.

I have:
```
#!/usr/bin/env bash
nwg-wrapper --script $(pwd)/mydate.sh --css "$(pwd)/mydate.css" --layer 3 --refresh 500 --alignment start 1>/dev/null 2>&1 &
sleep 2 && swaylock && pkill -f -2 nwg-wrapper
```

but swaylock keeps overlaying nwg-wrapper :(

**Comment by 10b14224cc** [comment]
I found this [here](https://www.reddit.com/r/swaywm/comments/11ig9z9/mucking_about_with_layers/):

```
Swaylock used to be rendered on the same layer (overlay), which is why your results depend on the surface creation order. Nowadays (sway 1.8) it uses [ext-session-lock-v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/ext-session-lock/ext-session-lock-v1.xml) protocol and it's no longer possible to draw anything above the lockscreen at all.
```

**Comment by bhepple** [comment]
I gave up on nwg-wrapper for use on the lockscreen (although I still use it on normal sway sessions to overlay help information eg in resize or move modes).

Instead I wrote some add-on modules for gtklock that provide the same information. It's all documented at https://github.com/jovanlanik/gtklock including the wiki there.

**Comment by 10b14224cc** [comment]
> I gave up on nwg-wrapper for use on the lockscreen (although I still use it on normal sway sessions to overlay help information eg in resize or move modes).
> 
> Instead I wrote some add-on modules for gtklock that provide the same information. It's all documented at https://github.com/jovanlanik/gtklock including the wiki there.

It looks like gtklock is based on wlr-layer-shell and wlr-input-inhibitor instead of ext-session-lock, thus is more insecure.
